// 小児不整脈薬 投与量データ
//
// 出典（2系統を照合のうえ使用）:
//  1) 「小児不整脈の診断・治療ガイドライン」日本小児循環器学会（2010年）  … source: 'old2010'
//  2) 「2020年改訂版 不整脈薬物治療ガイドライン」日本循環器学会/日本不整脈心電学会
//     JCS/JHRS 2020 Guideline on Pharmacotherapy of Cardiac Arrhythmias（2023年10月13日更新）
//     第11章「小児の不整脈」・表78「各種抗不整脈薬の適用，用法・用量：小児」    … source: 'jcs2020'
//
// 2系統の内容が食い違う場合は、より新しい jcs2020（特に表78）の値を優先して採用している。
// jcs2020 の表78に記載のない薬剤（ジルチアゼムなど）は old2010 の値を参考値として残し、
// その旨を明記している。
// source: 'general_practice' の項目は、いずれのガイドラインにも小児向けの具体的な
// mg/kg記載が無いため、一般的な小児救急領域の実務量を暫定的に採用している。
//
// 本データはオーダーの下書き支援であり、最終投与量は必ず現場（添付文書・院内基準）で確認すること。
// 各薬剤には計算の基準とした「標準投与量」（mg/kg等）を明記し、丸め処理後の実投与量が
// その標準投与量から何％ずれているかを検算できるようにしている（10％を超える場合は警告表示）。

// フローチャート/表の画像は原本PDFから図表部分のみを切り出したもの（本文は含まない）。
// 各画像の "page" は原本PDF内の実際のページ番号（1始まり）で、原本を直接開いて
// 前後の文脈まで確認できるよう参照リンクの生成に使う。
const GUIDELINE_SOURCES = {
  old2010: {
    title: '小児不整脈の診断・治療ガイドライン（日本小児循環器学会）',
    // このPC内のローカルパス。院内配布などで移動した場合はここを更新する。
    localPath: 'Y:/05_文献(旧Dropbox)/旧Dropbox/★じ　循環器/★ガイドライン/③不整脈/小児不整脈ガイドライン.pdf',
  },
  jcs2020: {
    title: '2020年改訂版 不整脈薬物治療ガイドライン（日本循環器学会/日本不整脈心電学会）第11章 小児の不整脈',
    url: 'https://www.j-circ.or.jp/cms/wp-content/uploads/2020/01/JCS2020_Ono.pdf',
  },
};

// 後方互換用（旧コードから参照されている場合に備えて残す）
const GUIDELINE_SOURCE = GUIDELINE_SOURCES.old2010;

function guidelinePdfLink(pageNum, sourceKey) {
  const src = GUIDELINE_SOURCES[sourceKey || 'old2010'];
  if (src.localPath) {
    return 'file:///' + encodeURI(src.localPath) + '#page=' + pageNum;
  }
  // ローカルパスを持たない（Web上の）出典は、ページ番号付きでURLに付与する
  return src.url + '#page=' + pageNum;
}

const ARRHYTHMIA_CATEGORIES = [
  {
    id: 'psvt',
    label: '発作性上室頻拍（PSVT）頻拍停止',
    shortLabel: 'PSVT（頻拍停止）',
    flowcharts: [
      {
        file: 'jcs2020_fig33_svt_stop.png',
        caption: '図33　小児持続性/反復性頻拍に対する頻拍発作の停止のフローチャート',
        page: 107,
        sourceKey: 'jcs2020',
      },
    ],
    items: [
      {
        kind: 'procedure',
        name: '迷走神経手技（息こらえ・アイスバッグ法・顔面浸水・頸動脈洞マッサージ）',
        badge: '血行動態安定時：第一',
        notes: [
          '氷水を満たしたビニール袋を前額部に10〜15秒あてる（気道閉塞に注意）。',
          '眼球圧迫は網膜剥離のリスクがあるため行わない。',
        ],
        source: 'jcs2020',
        sourcePage: 106,
      },
      {
        kind: 'drug',
        name: 'ATP（アデホスL）',
        badge: '迷走神経手技が無効な場合の第一選択薬（保険適用外）',
        stock: '20mg/2mL（10mg/mL）',
        dilution: '原液1mL（10mg）＋生理食塩水9mLで希釈 → 1mg/mL（2010年版ガイドラインの希釈法）',
        concMgPerMl: 1,
        doseType: 'mgPerKg',
        doseMinPerKg: 0.1,
        doseMaxPerKg: 0.3,
        route: 'できるだけ心臓に近い静脈から急速静注し、直後に5%糖液または生食で後押しする',
        round: { step: 0.1, direction: 'down' },
        roundReason: '過量では高度房室ブロックの遷延・徐脈のリスクがあるため切り下げ',
        notes: [
          '半減期8〜10秒と短い。ジピリダモール併用下で作用増強、キサンチン系併用下で作用減弱。',
          '気管支喘息では誘発に注意。',
        ],
        source: 'jcs2020',
        sourcePage: 106,
      },
      {
        kind: 'drug',
        name: 'ベラパミル',
        badge: 'ATP無効時',
        stock: '5mg/2mL（2.5mg/mL）',
        dilution: '原液のまま使用可（必要に応じ希釈し5分以上かけて投与）',
        concMgPerMl: 2.5,
        doseType: 'mgPerKg',
        dosePerKg: 0.1,
        route: '5分以上かけて緩徐に静注',
        round: { step: 0.1, direction: 'down' },
        roundReason: '禁忌年齢に近い患児での過量投与を避けるため切り下げ',
        notes: [
          { text: '新生児・乳児は禁忌（血圧低下など重篤な循環不全のリスク）。', warn: true },
          '顕性WPW症候群の心房細動には禁忌（心室細動移行の危険）。',
        ],
        source: 'jcs2020',
        sourcePage: 106,
      },
      {
        kind: 'drug',
        name: 'ジゴキシン（乳幼児）',
        badge: 'ATP・ベラパミルに次ぐ選択（乳幼児）',
        stock: '0.25mg/1mL',
        dilution: '原液1mL（0.25mg）＋生理食塩水9mLで希釈 → 0.025mg/mL',
        concMgPerMl: 0.025,
        doseType: 'mgPerKg',
        doseMinPerKg: 0.03,
        doseMaxPerKg: 0.05,
        route: '3〜4回に分割して静注（総量として）',
        round: { step: 0.1, direction: 'down' },
        roundReason: 'ジギタリス中毒（治療域が狭い）を避けるため必ず切り下げ',
        notes: [
          '顕性WPW症候群（デルタ波陽性）には投与しない。',
          '学童には「ジゴキシン（学童）」の量を用いる。',
        ],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'ジゴキシン（学童）',
        badge: 'ATP・ベラパミルに次ぐ選択（学童）',
        stock: '0.25mg/1mL',
        dilution: '原液1mL（0.25mg）＋生理食塩水9mLで希釈 → 0.025mg/mL',
        concMgPerMl: 0.025,
        doseType: 'mgPerKg',
        doseMinPerKg: 0.02,
        doseMaxPerKg: 0.04,
        route: '3〜4回に分割して静注（総量として）',
        round: { step: 0.1, direction: 'down' },
        roundReason: 'ジギタリス中毒（治療域が狭い）を避けるため必ず切り下げ',
        notes: ['顕性WPW症候群（デルタ波陽性）には投与しない。'],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'プロカインアミド（IA群）',
        badge: 'Na+チャネル遮断薬：ATP等が無効な場合',
        stock: '100mg/1mL（10%）',
        dilution: '原液1mL（100mg）＋生理食塩水9mLで希釈 → 10mg/mL',
        concMgPerMl: 10,
        doseType: 'mgPerKg',
        doseMinPerKg: 2,
        doseMaxPerKg: 10,
        route: '10分以上かけてゆっくり希釈静注（頻拍が停止すれば中止）',
        round: { step: 0.1, direction: 'down' },
        roundReason: '血圧低下・催不整脈のリスクがあるため切り下げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'ジソピラミド（IA群）',
        badge: 'Na+チャネル遮断薬：ATP等が無効な場合',
        stock: '50mg/5mL（10mg/mL）',
        dilution: '原液のまま、または希釈して使用',
        concMgPerMl: 10,
        doseType: 'mgPerKg',
        doseMinPerKg: 1,
        doseMaxPerKg: 2,
        maxDoseMg: 300,
        route: '5分以上かけて希釈静注',
        round: { step: 0.1, direction: 'down' },
        roundReason: '陰性変力作用・抗コリン作用があるため切り下げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'フレカイニド（IC群）',
        badge: 'Na+チャネル遮断薬：ATP等が無効な場合',
        stock: '50mg/5mL（10mg/mL）',
        dilution: '原液のまま、または希釈して使用',
        concMgPerMl: 10,
        doseType: 'mgPerKg',
        doseMinPerKg: 1,
        doseMaxPerKg: 2,
        maxDoseMg: 150,
        route: '10分間かけて希釈静注',
        round: { step: 0.1, direction: 'down' },
        roundReason: '催不整脈作用のリスクがあるため切り下げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'アミオダロン（JCS2020レジメン）',
        badge: '他の薬剤が無効な場合（洞調律化に時間を要する・血圧低下に注意）',
        stock: '150mg/3mL（50mg/mL）',
        dilution: '原液3mL（150mg）＋5%ブドウ糖液57mLで希釈 → 2.5mg/mL（計60mL）',
        concMgPerMl: 2.5,
        doseType: 'mgPerKg',
        dosePerKg: 2.5,
        route: '10分間で急速投与。その後、負荷投与1mg/kg/時を6時間→維持投与0.5mg/kg/時を42時間',
        round: { step: 0.1, direction: 'down' },
        roundReason: '血圧低下・徐脈などの副作用が用量依存性のため切り下げ',
        notes: ['血行動態不安定な頻拍が再発し再投与が必要な場合も同量（2.5mg/kg）を10分間で投与。'],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'アミオダロン（急速投与）',
        badge: '2010年版ガイドラインに基づく急速静注（5mg/kg）',
        stock: '150mg/3mL（50mg/mL）',
        dilution: '原液3mL（150mg）＋5%ブドウ糖液57mLで希釈 → 2.5mg/mL（計60mL）',
        concMgPerMl: 2.5,
        doseType: 'mgPerKg',
        dosePerKg: 5,
        route: '5分〜1時間かけて静注。以後10〜20mg/kg/日を維持量として3〜5日間使用',
        round: { step: 0.1, direction: 'down' },
        roundReason: '血圧低下・徐脈などの副作用が用量依存性のため切り下げ',
        notes: ['上記「JCS2020レジメン」（2.5mg/kg）とは別の投与方法。院内の使用実績・在庫に応じて選択する。'],
        source: 'old2010',
        sourcePage: 34,
      },
      {
        kind: 'procedure',
        name: '同期下DC（カルディオバージョン）',
        badge: '血行動態不安定・薬物治療抵抗性',
        doseType: 'joulePerKg',
        doseMinPerKg: 0.5,
        doseMaxPerKg: 2.0,
        round: { step: 1, direction: 'up' },
        roundReason: 'エネルギー不足による除細動失敗を避けるため切り上げ',
        notes: ['心肺蘇生を行いながら必要に応じて実施。血行動態が不良で上室頻拍か診断困難な場合も適応。'],
        source: 'jcs2020',
        sourcePage: 106,
      },
    ],
  },

  {
    id: 'afib_aflutter',
    label: '心房細動・心房粗動（レートコントロール）',
    shortLabel: '心房細動・粗動',
    flowcharts: [
      {
        file: 'fig2_afib_rate_control.png',
        caption: '図2　心房細動の心拍調節（JCS2020には小児専用フローチャートなし。薬用量はJCS2020表78で照合済み）',
        page: 7,
        sourceKey: 'old2010',
      },
      {
        file: 'fig3_aflutter_treatment.png',
        caption: '図3　心房粗動の治療（同上）',
        page: 10,
        sourceKey: 'old2010',
      },
    ],
    items: [
      {
        kind: 'drug',
        name: 'プロプラノロール',
        badge: '心機能良好時：第一選択（β遮断薬）',
        stock: '2mg/2mL（1mg/mL）',
        dilution: '原液のまま使用可',
        concMgPerMl: 1,
        doseType: 'mgPerKg',
        doseMinPerKg: 0.05,
        doseMaxPerKg: 0.1,
        route: '10分以上かけてゆっくり静注',
        round: { step: 0.1, direction: 'down' },
        roundReason: '徐脈・心収縮力低下のリスクがあるため切り下げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'ベラパミル',
        badge: '心機能良好時：第一選択（Ca拮抗薬）',
        stock: '5mg/2mL（2.5mg/mL）',
        dilution: '原液のまま使用可',
        concMgPerMl: 2.5,
        doseType: 'mgPerKg',
        dosePerKg: 0.1,
        route: '5分以上かけてゆっくり静注',
        round: { step: 0.1, direction: 'down' },
        roundReason: '禁忌年齢に近い患児での過量投与を避けるため切り下げ',
        notes: [
          { text: '新生児・乳児は禁忌。', warn: true },
          'デルタ波陽性WPW症候群の心房細動には禁忌（心室細動移行の危険）。',
        ],
        source: 'jcs2020',
        sourcePage: 106,
      },
      {
        kind: 'drug',
        name: 'ジルチアゼム',
        badge: 'ベラパミルの代替',
        stock: '添付規格に応じて調製',
        dilution: '希釈して使用（濃度は現場の在庫に合わせて確認）',
        concMgPerMl: 5,
        doseType: 'mgPerKg',
        doseMinPerKg: 0.1,
        doseMaxPerKg: 0.2,
        route: '2〜10分かけてゆっくり静注',
        round: { step: 0.1, direction: 'down' },
        roundReason: '2歳以下で心血管虚脱のリスクがあるため切り下げ',
        notes: [
          '2歳以下では投与に注意。',
          '※ JCS2020の表78には記載がなく、2010年版ガイドラインに基づく参考値。',
        ],
        source: 'old2010',
        sourcePage: 33,
      },
      {
        kind: 'drug',
        name: 'ジゴキシン（乳幼児）',
        badge: '心機能低下時：第一選択（乳幼児）',
        stock: '0.25mg/1mL',
        dilution: '原液1mL（0.25mg）＋生理食塩水9mLで希釈 → 0.025mg/mL',
        concMgPerMl: 0.025,
        doseType: 'mgPerKg',
        doseMinPerKg: 0.03,
        doseMaxPerKg: 0.05,
        route: '3〜4回に分割して静注（総量として）',
        round: { step: 0.1, direction: 'down' },
        roundReason: 'ジギタリス中毒（治療域が狭い）を避けるため必ず切り下げ',
        notes: [
          '顕性WPW症候群（デルタ波陽性）には投与しない。',
          '学童には「ジゴキシン（学童）」の量を用いる。',
        ],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'ジゴキシン（学童）',
        badge: '心機能低下時：第一選択（学童）',
        stock: '0.25mg/1mL',
        dilution: '原液1mL（0.25mg）＋生理食塩水9mLで希釈 → 0.025mg/mL',
        concMgPerMl: 0.025,
        doseType: 'mgPerKg',
        doseMinPerKg: 0.02,
        doseMaxPerKg: 0.04,
        route: '3〜4回に分割して静注（総量として）',
        round: { step: 0.1, direction: 'down' },
        roundReason: 'ジギタリス中毒（治療域が狭い）を避けるため必ず切り下げ',
        notes: ['顕性WPW症候群（デルタ波陽性）には投与しない。'],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'procedure',
        name: '同期下DC（心房細動）',
        doseType: 'joulePerKg',
        doseMinPerKg: 0.5,
        doseMaxPerKg: 2.0,
        round: { step: 1, direction: 'up' },
        roundReason: 'エネルギー不足による除細動失敗を避けるため切り上げ',
        notes: ['施行前に絶食・鎮静/麻酔を要する。心内血栓の有無を要確認。'],
        source: 'jcs2020',
        sourcePage: 106,
      },
      {
        kind: 'procedure',
        name: '同期下DC（心房粗動、血行動態不安定時）',
        doseType: 'joulePerKg',
        doseMinPerKg: 0.5,
        doseMaxPerKg: 2.0,
        round: { step: 1, direction: 'up' },
        roundReason: 'エネルギー不足による除細動失敗を避けるため切り上げ',
        notes: ['新生児の心房粗動では同期下カルディオバージョンで洞調律化87%との報告。'],
        source: 'jcs2020',
        sourcePage: 111,
      },
    ],
  },

  {
    id: 'vt_stable',
    label: '心室頻拍（脈あり・血行動態安定）',
    shortLabel: 'VT（脈あり）',
    flowcharts: [
      {
        file: 'jcs2020_fig36_vt_stop.png',
        caption: '図36　小児患者の心室頻拍停止のフローチャート',
        page: 112,
        sourceKey: 'jcs2020',
      },
    ],
    items: [
      {
        kind: 'drug',
        name: 'ベラパミル',
        badge: 'RBBB＋LAD型：第一選択（Ca拮抗薬）',
        stock: '5mg/2mL（2.5mg/mL）',
        dilution: '原液のまま使用可',
        concMgPerMl: 2.5,
        doseType: 'mgPerKg',
        dosePerKg: 0.1,
        route: '5分以上かけて緩徐に静注',
        round: { step: 0.1, direction: 'down' },
        roundReason: '乳児以下は禁忌のため過量を避けて切り下げ',
        notes: [{ text: '乳児以下には禁忌（ベラパミル感受性心室頻拍の項）。', warn: true }],
        source: 'jcs2020',
        sourcePage: 113,
      },
      {
        kind: 'drug',
        name: 'プロプラノロール',
        badge: 'RBBB＋LAD型：第二選択 ／ LBBB＋RAD型：第一選択（β遮断薬）',
        stock: '2mg/2mL（1mg/mL）',
        dilution: '原液のまま使用可',
        concMgPerMl: 1,
        doseType: 'mgPerKg',
        doseMinPerKg: 0.05,
        doseMaxPerKg: 0.1,
        route: '10分以上かけてゆっくり静注',
        round: { step: 0.1, direction: 'down' },
        roundReason: '徐脈・心収縮力低下のリスクがあるため切り下げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'ジソピラミド',
        badge: 'RBBB＋LAD型：第二選択（Na+チャネル遮断薬）',
        stock: '50mg/5mL（10mg/mL）',
        dilution: '原液のまま、または希釈して使用',
        concMgPerMl: 10,
        doseType: 'mgPerKg',
        doseMinPerKg: 1,
        doseMaxPerKg: 2,
        maxDoseMg: 300,
        route: '5分以上かけて希釈静注',
        round: { step: 0.1, direction: 'down' },
        roundReason: '陰性変力作用があるため切り下げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'フレカイニド',
        badge: '各型共通：第一選択（Na+チャネル遮断薬）',
        stock: '50mg/5mL（10mg/mL）',
        dilution: '原液のまま、または希釈して使用',
        concMgPerMl: 10,
        doseType: 'mgPerKg',
        doseMinPerKg: 1,
        doseMaxPerKg: 2,
        maxDoseMg: 150,
        route: '10分間かけて希釈静注',
        round: { step: 0.1, direction: 'down' },
        roundReason: '催不整脈作用のリスクがあるため切り下げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'リドカイン',
        badge: 'LBBB＋RAD型・その他：第一選択',
        stock: '2%（100mg/5mL＝20mg/mL）',
        dilution: '原液1mL（20mg）＋生理食塩水9mLで希釈 → 2mg/mL',
        concMgPerMl: 2,
        doseType: 'mgPerKg',
        dosePerKg: 1,
        route: '希釈静注。有効なら0.025〜0.05mg/kg/分で持続点滴',
        round: { step: 0.1, direction: 'down' },
        roundReason: '血行動態安定例のため安全側（切り下げ）とし、必要なら再投与で調整',
        notes: [],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'メキシレチン',
        badge: 'LBBB＋RAD型・その他：第一選択',
        stock: '250mg/10mL（25mg/mL）',
        dilution: '5%ブドウ糖液等で希釈し使用',
        concMgPerMl: 25,
        doseType: 'mgPerKg',
        doseMinPerKg: 2,
        doseMaxPerKg: 3,
        route: '5〜10分で希釈静注。有効なら0.4〜0.6mg/kg/時間で持続点滴',
        round: { step: 0.1, direction: 'down' },
        roundReason: '陰性変力作用・中枢神経系副作用のリスクがあるため切り下げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'ATP（アデホスL）',
        badge: 'LBBB＋RAD型：第一選択（保険適用外）',
        stock: '20mg/2mL（10mg/mL）',
        dilution: '原液1mL（10mg）＋生理食塩水9mLで希釈 → 1mg/mL（2010年版ガイドラインの希釈法）',
        concMgPerMl: 1,
        doseType: 'mgPerKg',
        doseMinPerKg: 0.1,
        doseMaxPerKg: 0.3,
        route: '急速静注',
        round: { step: 0.1, direction: 'down' },
        roundReason: '過量投与時の高度房室ブロック遷延を避けるため切り下げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 112,
      },
      {
        kind: 'infusion',
        name: 'ランジオロール',
        badge: 'LBBB＋RAD型：第一選択（超短時間作用型β遮断薬）',
        stock: '添付規格に応じて調製',
        dilution: '例：50mg製剤を希釈し1mg/mLに調整',
        concMcgPerMl: 1000,
        doseType: 'mcgPerKgMin',
        doseMinPerKg: 2.5,
        doseMaxPerKg: 80,
        route: '2.5μg/kg/分で開始し、数分ごとに倍量ずつ漸増（最大80μg/kg/分）',
        round: { step: 0.1, direction: 'down' },
        roundReason: 'β遮断薬の過量投与（高度徐脈・血圧低下）を避けるため切り下げ',
        notes: ['※ JCS2020の表78には掲載されていないため、2010年版ガイドラインに基づく参考値。'],
        source: 'old2010',
        sourcePage: 37,
      },
      {
        kind: 'drug',
        name: 'アミオダロン（JCS2020レジメン）',
        badge: '各型共通：薬剤抵抗性時の第二選択',
        stock: '150mg/3mL（50mg/mL）',
        dilution: '原液3mL（150mg）＋5%ブドウ糖液57mLで希釈 → 2.5mg/mL（計60mL）',
        concMgPerMl: 2.5,
        doseType: 'mgPerKg',
        dosePerKg: 2.5,
        route: '10分間で急速投与。その後、負荷投与1mg/kg/時を6時間→維持投与0.5mg/kg/時を42時間',
        round: { step: 0.1, direction: 'down' },
        roundReason: '血圧低下・徐脈などの副作用が用量依存性のため切り下げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'アミオダロン（急速投与）',
        badge: '2010年版ガイドラインに基づく急速静注（5mg/kg）',
        stock: '150mg/3mL（50mg/mL）',
        dilution: '原液3mL（150mg）＋5%ブドウ糖液57mLで希釈 → 2.5mg/mL（計60mL）',
        concMgPerMl: 2.5,
        doseType: 'mgPerKg',
        dosePerKg: 5,
        route: '5分〜1時間かけて静注。以後10〜20mg/kg/日を維持量として3〜5日間使用',
        round: { step: 0.1, direction: 'down' },
        roundReason: '血圧低下・徐脈などの副作用が用量依存性のため切り下げ',
        notes: ['上記「JCS2020レジメン」（2.5mg/kg）とは別の投与方法。院内の使用実績・在庫に応じて選択する。'],
        source: 'old2010',
        sourcePage: 34,
      },
      {
        kind: 'drug',
        name: 'ニフェカラント',
        badge: '各型共通：薬剤抵抗性時の第二選択（Kチャネル遮断薬）',
        stock: '添付規格に応じて調製',
        dilution: '5%ブドウ糖液で希釈し1mg/mLに調整',
        concMgPerMl: 1,
        doseType: 'mgPerKg',
        dosePerKg: 0.3,
        route: '10分かけて静注。維持量0.2〜0.4mg/kg/時',
        round: { step: 0.1, direction: 'down' },
        roundReason: 'QT延長・催不整脈のリスクがあるため切り下げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'procedure',
        name: '同期下DCショック（カルディオバージョン）またはペーシング',
        badge: '薬剤抵抗性時',
        doseType: 'joulePerKg',
        doseMinPerKg: 1,
        doseMaxPerKg: 2,
        escalation: '不成功であれば4 J/kgまで増量',
        round: { step: 1, direction: 'up' },
        roundReason: 'エネルギー不足による除細動失敗を避けるため切り上げ',
        notes: [
          { text: '必ず「同期」モードで実施すること（非同期で行うとVFを誘発する危険がある）。', warn: true },
        ],
        source: 'jcs2020',
        sourcePage: 111,
      },
    ],
  },

  {
    id: 'vf_pulseless_vt',
    label: '心室細動・無脈性心室頻拍（心停止）',
    shortLabel: 'VF・無脈性VT',
    flowcharts: [
      {
        file: 'fig10_vf_pulseless_vt_acute.png',
        caption: '図10　多形性心室頻拍・心室細動・無脈性心室頻拍：発作時の治療（JCS2020には小児専用フローチャートなし。薬用量はJCS2020表78で照合済み）',
        page: 20,
        sourceKey: 'old2010',
      },
    ],
    items: [
      {
        kind: 'procedure',
        name: '除細動（非同期）',
        badge: 'CPR（PALS）と並行して施行',
        doseType: 'joulePerKg',
        dosePerKg: 4,
        round: { step: 1, direction: 'up' },
        roundReason: 'エネルギー不足による除細動失敗を避けるため切り上げ',
        notes: ['初回から4 J/kgに固定（漸増しない）。以降も4 J/kgで反復可。'],
        source: 'jcs2020',
        sourcePage: 111,
      },
      {
        kind: 'drug',
        name: 'アドレナリン',
        badge: 'DCショック無効時、3〜5分毎',
        stock: '1mg/1mL（0.1%、ボスミン原液）',
        dilution: '原液1mL（1mg）＋生理食塩水9mLで希釈 → 0.1mg/mL',
        concMgPerMl: 0.1,
        doseType: 'mgPerKg',
        dosePerKg: 0.01,
        maxDoseMg: 1,
        route: '急速静注（またはIO）、3〜5分毎に反復',
        round: { step: 0.1, direction: 'up' },
        roundReason: '心停止時は不足の方が致命的であるため切り上げ',
        notes: ['小児蘇生（PALS）の標準量。JCS2020の抗不整脈薬表78には掲載なし（蘇生薬のため）。'],
        source: 'general_practice',
      },
      {
        kind: 'drug',
        name: 'アミオダロン（JCS2020レジメン）',
        badge: '除細動抵抗性',
        stock: '150mg/3mL（50mg/mL）',
        dilution: '原液3mL（150mg）＋5%ブドウ糖液57mLで希釈 → 2.5mg/mL（計60mL）',
        concMgPerMl: 2.5,
        doseType: 'mgPerKg',
        dosePerKg: 2.5,
        route: '10分間で急速静注（bolus）。再発時は同量を反復可',
        round: { step: 0.1, direction: 'up' },
        roundReason: '心停止時は不足の方が致命的であるため切り上げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'アミオダロン（急速投与）',
        badge: '2010年版ガイドラインに基づく急速静注（5mg/kg）',
        stock: '150mg/3mL（50mg/mL）',
        dilution: '原液3mL（150mg）＋5%ブドウ糖液57mLで希釈 → 2.5mg/mL（計60mL）',
        concMgPerMl: 2.5,
        doseType: 'mgPerKg',
        dosePerKg: 5,
        route: '5分〜1時間かけて急速静注（bolus）',
        round: { step: 0.1, direction: 'up' },
        roundReason: '心停止時は不足の方が致命的であるため切り上げ',
        notes: ['上記「JCS2020レジメン」（2.5mg/kg）とは別の投与方法。院内の使用実績・在庫に応じて選択する。'],
        source: 'old2010',
        sourcePage: 34,
      },
      {
        kind: 'drug',
        name: 'リドカイン',
        badge: 'アミオダロンの代替（第二選択）',
        stock: '2%（100mg/5mL＝20mg/mL）',
        dilution: '原液1mL（20mg）＋生理食塩水9mLで希釈 → 2mg/mL',
        concMgPerMl: 2,
        doseType: 'mgPerKg',
        dosePerKg: 1,
        route: '急速静注（bolus）。有効なら0.025〜0.05mg/kg/分で持続点滴',
        round: { step: 0.1, direction: 'up' },
        roundReason: '心停止時は不足の方が致命的であるため切り上げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'ニフェカラント',
        badge: '除細動抵抗性の代替（Kチャネル遮断薬）',
        stock: '添付規格に応じて調製',
        dilution: '5%ブドウ糖液で希釈し1mg/mLに調整',
        concMgPerMl: 1,
        doseType: 'mgPerKg',
        dosePerKg: 0.3,
        route: '10分かけて静注（維持量0.2〜0.4mg/kg/時）',
        round: { step: 0.1, direction: 'down' },
        roundReason: 'QT延長・催不整脈のリスクがあるため切り下げ',
        notes: ['保険適応外。'],
        source: 'jcs2020',
        sourcePage: 124,
      },
    ],
  },

  {
    id: 'bradycardia',
    label: '徐脈性不整脈・症候性房室ブロック',
    shortLabel: '徐脈・房室ブロック',
    flowcharts: [
      {
        file: 'table13_14_bradycardia.png',
        caption: '表13/表14　徐脈性不整脈の原因／洞不全症候群の分類（JCS2020には小児専用フローチャートなし）',
        page: 31,
        sourceKey: 'old2010',
      },
      {
        file: 'table15_pacemaker.png',
        caption: '表15　小児のペースメーカの適応ガイドライン',
        page: 33,
        sourceKey: 'old2010',
      },
    ],
    items: [
      {
        kind: 'drug',
        name: 'アトロピン',
        badge: '迷走神経性の徐脈・房室伝導障害',
        stock: '0.5mg/1mL',
        dilution: '原液1mL（0.5mg）＋生理食塩水9mLで希釈 → 0.05mg/mL',
        concMgPerMl: 0.05,
        doseType: 'mgPerKg',
        doseMinPerKg: 0.01,
        doseMaxPerKg: 0.02,
        maxDoseNote: '最大量：乳幼児1mg、年長児2mg（2010年版ガイドラインによる参考値）',
        route: '静注（5分以上あけて同量まで追加可）',
        round: { step: 0.1, direction: 'up' },
        roundReason: '徐脈遷延を避けるため切り上げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'infusion',
        name: 'イソプロテレノール',
        badge: 'アトロピン無効・高度徐脈（ペーシングまでの橋渡し）',
        stock: '0.2mg/1mL（200μg/mL）',
        dilution: '原液1mL（200μg）＋5%ブドウ糖液49mLで希釈 → 4μg/mL（計50mL）',
        concMcgPerMl: 4,
        doseType: 'mcgPerKgMin',
        doseMinPerKg: 0.1,
        doseMaxPerKg: 1,
        route: '持続静注。心拍数100/分程度を目標に少量から漸増して調整',
        round: { step: 0.1, direction: 'down' },
        roundReason: '過量域での頻脈・不整脈助長を避けるため切り下げ（低用量から漸増が原則）',
        notes: [
          '※ JCS2020の小児専用表78には掲載がなく、QT延長症候群の章にある小児用量（0.1〜1μg/kg/分）を採用。',
          '2010年版ガイドラインの記載（0.01〜0.03μg/kg/分）より高値のため、必ず心拍数を見ながら少量から開始する。',
          '先天性QT延長症候群が疑われる場合はQT延長を悪化させる可能性があり注意。',
        ],
        source: 'jcs2020',
        sourcePage: 96,
      },
      {
        kind: 'drug',
        name: 'アドレナリン',
        badge: '心停止に近い高度徐脈・心停止時',
        stock: '1mg/1mL（0.1%、ボスミン原液）',
        dilution: '原液1mL（1mg）＋生理食塩水9mLで希釈 → 0.1mg/mL',
        concMgPerMl: 0.1,
        doseType: 'mgPerKg',
        dosePerKg: 0.01,
        maxDoseMg: 1,
        route: '急速静注（またはIO）',
        round: { step: 0.1, direction: 'up' },
        roundReason: '心停止に近い状況では不足の方が致命的であるため切り上げ',
        notes: [],
        source: 'general_practice',
      },
    ],
  },

  {
    id: 'tdp_polymorphic_vt',
    label: 'Torsade de pointes・多形性心室頻拍',
    shortLabel: 'TdP・多形性VT',
    flowcharts: [
      {
        file: 'fig10_vf_pulseless_vt_acute.png',
        caption: '図10　多形性心室頻拍・心室細動・無脈性心室頻拍：発作時の治療（JCS2020には小児専用フローチャートなし）',
        page: 20,
        sourceKey: 'old2010',
      },
      {
        file: 'fig11_vf_pulseless_vt_prevent.png',
        caption: '図11　多形性心室頻拍・心室細動・無脈性心室頻拍の予防',
        page: 21,
        sourceKey: 'old2010',
      },
    ],
    items: [
      {
        kind: 'drug',
        name: '硫酸マグネシウム',
        badge: 'QT延長を伴うTdPの急性期治療',
        stock: '20%（200mg/mL）',
        dilution: '原液1mL（200mg）＋生理食塩水9mLで希釈 → 20mg/mL',
        concMgPerMl: 20,
        doseType: 'mgPerKg',
        doseMinPerKg: 20,
        doseMaxPerKg: 40,
        route: '1〜2分で静注',
        round: { step: 0.1, direction: 'down' },
        roundReason: '呼吸抑制・房室伝導障害などMg中毒を避けるため切り下げ',
        notes: ['腎機能障害例では高Mg血症をきたしやすいため血清Mg値をモニタリング。'],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'infusion',
        name: '硫酸マグネシウム（維持点滴）',
        badge: 'ボーラス後、効果があれば持続投与',
        stock: '20%（200mg/mL）',
        dilution: '原液1mL（200mg）＋生理食塩水9mLで希釈 → 20mg/mL（＝20,000μg/mL相当として計算）',
        concMcgPerMl: 20000,
        doseType: 'mcgPerKgMin',
        doseMinPerKg: 50,
        doseMaxPerKg: 300,
        route: '持続静注',
        round: { step: 0.1, direction: 'down' },
        roundReason: 'Mg中毒（血圧低下・呼吸抑制）を避けるため切り下げ',
        notes: ['JCS2020の単位表記（0.05〜0.3mg/kg/分）をμg/kg/分に換算（×1000）して計算。'],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'procedure',
        name: '除細動（無脈性・持続する場合）',
        doseType: 'joulePerKg',
        doseMinPerKg: 1,
        doseMaxPerKg: 2,
        escalation: '不成功であれば4 J/kgまで増量',
        round: { step: 1, direction: 'up' },
        roundReason: 'エネルギー不足による除細動失敗を避けるため切り上げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 111,
      },
      {
        kind: 'drug',
        name: 'プロプラノロール',
        badge: 'CPVT疑いの場合（β遮断薬）',
        stock: '2mg/2mL（1mg/mL）',
        dilution: '原液のまま使用可',
        concMgPerMl: 1,
        doseType: 'mgPerKg',
        doseMinPerKg: 0.05,
        doseMaxPerKg: 0.1,
        route: '10分以上かけてゆっくり静注',
        round: { step: 0.1, direction: 'down' },
        roundReason: '徐脈・心収縮力低下のリスクがあるため切り下げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'ATP（アデホスL）',
        badge: 'CPVT疑いの場合（保険適用外）',
        stock: '20mg/2mL（10mg/mL）',
        dilution: '原液1mL（10mg）＋生理食塩水9mLで希釈 → 1mg/mL（2010年版ガイドラインの希釈法）',
        concMgPerMl: 1,
        doseType: 'mgPerKg',
        doseMinPerKg: 0.1,
        doseMaxPerKg: 0.3,
        route: '急速静注',
        round: { step: 0.1, direction: 'down' },
        roundReason: '過量投与時の高度房室ブロック遷延を避けるため切り下げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'ベラパミル',
        badge: 'CPVT疑いの場合',
        stock: '5mg/2mL（2.5mg/mL）',
        dilution: '原液のまま使用可',
        concMgPerMl: 2.5,
        doseType: 'mgPerKg',
        dosePerKg: 0.1,
        route: '5分以上かけて緩徐に静注',
        round: { step: 0.1, direction: 'down' },
        roundReason: '乳児以下は禁忌のため過量を避けて切り下げ',
        notes: [{ text: '乳児以下には禁忌。', warn: true }],
        source: 'jcs2020',
        sourcePage: 113,
      },
      {
        kind: 'drug',
        name: 'アミオダロン（JCS2020レジメン）',
        badge: '非CPVTの場合',
        stock: '150mg/3mL（50mg/mL）',
        dilution: '原液3mL（150mg）＋5%ブドウ糖液57mLで希釈 → 2.5mg/mL（計60mL）',
        concMgPerMl: 2.5,
        doseType: 'mgPerKg',
        dosePerKg: 2.5,
        route: '10分間で投与（無脈性の場合は急速静注）。以後、負荷1mg/kg/時×6時間→維持0.5mg/kg/時×42時間',
        round: { step: 0.1, direction: 'down' },
        roundReason: '血圧低下・徐脈などの副作用が用量依存性のため切り下げ',
        notes: [],
        source: 'jcs2020',
        sourcePage: 124,
      },
      {
        kind: 'drug',
        name: 'アミオダロン（急速投与）',
        badge: '2010年版ガイドラインに基づく急速静注（5mg/kg・非CPVTの場合）',
        stock: '150mg/3mL（50mg/mL）',
        dilution: '原液3mL（150mg）＋5%ブドウ糖液57mLで希釈 → 2.5mg/mL（計60mL）',
        concMgPerMl: 2.5,
        doseType: 'mgPerKg',
        dosePerKg: 5,
        route: '5分〜1時間かけて静注（無脈性の場合は急速静注）',
        round: { step: 0.1, direction: 'down' },
        roundReason: '血圧低下・徐脈などの副作用が用量依存性のため切り下げ',
        notes: ['上記「JCS2020レジメン」（2.5mg/kg）とは別の投与方法。院内の使用実績・在庫に応じて選択する。'],
        source: 'old2010',
        sourcePage: 34,
      },
      {
        kind: 'drug',
        name: 'ニフェカラント',
        badge: '非CPVTの場合（Kチャネル遮断薬）',
        stock: '添付規格に応じて調製',
        dilution: '5%ブドウ糖液で希釈し1mg/mLに調整',
        concMgPerMl: 1,
        doseType: 'mgPerKg',
        dosePerKg: 0.3,
        route: '10分かけて静注（維持量0.2〜0.4mg/kg/時）',
        round: { step: 0.1, direction: 'down' },
        roundReason: 'QT延長・催不整脈のリスクがあるため切り下げ',
        notes: ['保険適応外。QT延長を助長するため使用可否を要検討。'],
        source: 'jcs2020',
        sourcePage: 124,
      },
    ],
  },
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { ARRHYTHMIA_CATEGORIES, GUIDELINE_SOURCES, GUIDELINE_SOURCE, guidelinePdfLink };
}
